create table if not exists public.employees (
  id text primary key,
  name text not null,
  role text not null,
  department text not null,
  description text default '',
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.company_events (
  id uuid primary key default gen_random_uuid(),
  image_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.what_we_do (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  text text default '',
  category_order integer not null default 0,
  card_order integer not null default 0
);

create table if not exists public.archive_entries (
  key text primary key,
  label text not null,
  title text not null,
  text text default '',
  sort_order integer not null default 0
);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  number text not null,
  name text not null,
  logo_url text,
  url text,
  category text not null,
  description text default ''
);

alter table public.employees alter column id type text using id::text;

alter table public.employees enable row level security;
alter table public.company_events enable row level security;
alter table public.what_we_do enable row level security;
alter table public.archive_entries enable row level security;
alter table public.groups enable row level security;

drop policy if exists "Public can view employees" on public.employees;
drop policy if exists "Authenticated admins manage employees" on public.employees;
drop policy if exists "Public can view company events" on public.company_events;
drop policy if exists "Authenticated admins manage company events" on public.company_events;
drop policy if exists "Public can view what we do" on public.what_we_do;
drop policy if exists "Authenticated admins manage what we do" on public.what_we_do;
drop policy if exists "Public can view archive" on public.archive_entries;
drop policy if exists "Authenticated admins manage archive" on public.archive_entries;
drop policy if exists "Public can view groups" on public.groups;
drop policy if exists "Authenticated admins manage groups" on public.groups;

create policy "Public can view employees" on public.employees for select using (true);
create policy "Authenticated admins manage employees" on public.employees for all to authenticated using (true) with check (true);
create policy "Public can view company events" on public.company_events for select using (true);
create policy "Authenticated admins manage company events" on public.company_events for all to authenticated using (true) with check (true);
create policy "Public can view what we do" on public.what_we_do for select using (true);
create policy "Authenticated admins manage what we do" on public.what_we_do for all to authenticated using (true) with check (true);
create policy "Public can view archive" on public.archive_entries for select using (true);
create policy "Authenticated admins manage archive" on public.archive_entries for all to authenticated using (true) with check (true);
create policy "Public can view groups" on public.groups for select using (true);
create policy "Authenticated admins manage groups" on public.groups for all to authenticated using (true) with check (true);
